import fs from 'fs-extra';
import { dirname, join } from 'node:path';
import { stringify } from 'yaml';
import type { Command } from 'commander';
import type { Glossary, LocaleMetadata, ProjectConfig, ReleaseBase } from '@store-release-kit/core';
import { logger } from '../utils/logger.js';

interface InitOptions {
  appId?: string;
  defaultLocale?: string;
  targetLocales?: string;
  force?: boolean;
}

interface InitTemplate {
  config: ProjectConfig;
  glossary: Glossary;
  base: ReleaseBase;
  sourceLocale: LocaleMetadata;
  enUSLocale: LocaleMetadata;
}

async function writeYamlIfAllowed(
  filePath: string,
  value: unknown,
  force: boolean,
): Promise<boolean> {
  if (!force && (await fs.pathExists(filePath))) {
    return false;
  }

  await fs.ensureDir(dirname(filePath));
  await fs.writeFile(filePath, stringify(value), 'utf8');
  return true;
}

function parseTargetLocales(defaultLocale: string, targetLocales?: string): string[] {
  const parsed = targetLocales
    ? targetLocales
        .split(',')
        .map((locale) => locale.trim())
        .filter(Boolean)
    : [defaultLocale, 'en-US'];

  return [...new Set(parsed.includes(defaultLocale) ? parsed : [defaultLocale, ...parsed])];
}

function createConfig(
  appId: string,
  defaultLocale: string,
  targetLocales: string[],
): ProjectConfig {
  return {
    appId,
    platform: 'ios',
    defaultLocale,
    targetLocales,
    store: {
      provider: 'mock',
    },
    rules: {
      requireReviewBeforePush: true,
      allowMachineTranslation: false,
      maxKeywordsCount: 100,
    },
  };
}

function createGlossary(): Glossary {
  return {
    terms: [
      {
        source: 'App',
        translations: {
          'en-US': 'App',
        },
        locked: true,
        note: '示例锁定术语。',
      },
    ],
  };
}

function createLocales(defaultLocale: string): Pick<InitTemplate, 'sourceLocale' | 'enUSLocale'> {
  const sourceLocale: LocaleMetadata = {
    locale: defaultLocale,
    name: '示例应用',
    subtitle: '版本发布信息管理',
    promotionalText: '用 Git 管理应用商店发布文案。',
    description: '这是 store-release-kit 初始化生成的示例描述。',
    keywords: ['发布', '本地化', '应用商店'],
    whatsNew: '初始化版本发布说明。',
    supportUrl: 'https://example.com/support',
    marketingUrl: 'https://example.com',
    reviewStatus: 'human-reviewed',
  };

  return {
    sourceLocale,
    enUSLocale: {
      ...sourceLocale,
      locale: 'en-US',
      name: 'Example App',
      subtitle: 'Release metadata management',
      promotionalText: 'Manage App Store copy with Git.',
      description: 'This is a sample description generated by store-release-kit init.',
      keywords: ['release', 'localization', 'app-store'],
      whatsNew: 'Initial release notes.',
    },
  };
}

function createInitTemplate(options: InitOptions, version: string): InitTemplate {
  const defaultLocale = options.defaultLocale ?? 'zh-Hans';
  const targetLocales = parseTargetLocales(defaultLocale, options.targetLocales);
  const locales = createLocales(defaultLocale);

  return {
    config: createConfig(options.appId ?? 'com.example.app', defaultLocale, targetLocales),
    glossary: createGlossary(),
    base: {
      version,
      sourceLocale: defaultLocale,
      status: 'draft',
      createdAt: new Date().toISOString(),
      notes: ['Initial release metadata draft.'],
    },
    ...locales,
  };
}

async function writeInitTemplate(
  projectDir: string,
  version: string,
  template: InitTemplate,
  force: boolean,
): Promise<number> {
  const writes = [
    writeYamlIfAllowed(join(projectDir, 'store-release.config.yml'), template.config, force),
    writeYamlIfAllowed(join(projectDir, 'glossary.yml'), template.glossary, force),
    writeYamlIfAllowed(join(projectDir, 'releases', version, 'base.yml'), template.base, force),
    writeYamlIfAllowed(
      join(projectDir, 'releases', version, 'locales', `${template.sourceLocale.locale}.yml`),
      template.sourceLocale,
      force,
    ),
    writeYamlIfAllowed(
      join(projectDir, 'releases', version, 'locales', 'en-US.yml'),
      template.enUSLocale,
      force,
    ),
  ];

  const results = await Promise.all(writes);
  return results.filter(Boolean).length;
}

export async function runInitCommand(projectDir: string, options: InitOptions): Promise<void> {
  const version = '0.1.0';
  const template = createInitTemplate(options, version);
  const createdCount = await writeInitTemplate(
    projectDir,
    version,
    template,
    options.force ?? false,
  );

  logger.success(`初始化完成：创建/覆盖 ${createdCount} 个文件。`);
  logger.info(`下一步：store-release validate --version ${version}`);
  logger.info(
    `导出 Fastlane metadata：store-release export --version ${version} --format fastlane`,
  );
}

export function registerInitCommand(program: Command): void {
  program
    .command('init')
    .description('Initialize release metadata files in the current directory.')
    .option('--app-id <id>', 'App identifier', 'com.example.app')
    .option('--default-locale <locale>', 'Default source locale', 'zh-Hans')
    .option('--target-locales <locales>', 'Comma-separated target locales')
    .option('--force', 'Overwrite existing files', false)
    .action(async (options: InitOptions) => {
      await runInitCommand(process.cwd(), options);
    });
}
