import type { LocaleMetadata } from '@store-release-kit/core';
import type { TranslateReleaseInput, TranslatedRelease, TranslatorProvider } from '../types.js';

function translateText(text: string | undefined, locale: string): string | undefined {
  if (!text) {
    return undefined;
  }

  return `[${locale}] ${text}`;
}

function translateKeywords(keywords: string[] | undefined, locale: string): string[] | undefined {
  return keywords?.map((keyword) => `${keyword}-${locale}`);
}

function applyLockedTerms(
  text: string | undefined,
  input: TranslateReleaseInput,
  locale: string,
): string | undefined {
  if (!text || !input.glossary) {
    return text;
  }

  let result = text;

  for (const term of input.glossary.terms) {
    if (!term.locked) {
      continue;
    }

    const translatedTerm = term.translations[locale];
    if (translatedTerm) {
      result = result.replaceAll(term.source, translatedTerm);
    }
  }

  return result;
}

export class MockTranslator implements TranslatorProvider {
  name = 'mock' as const;

  async translateRelease(input: TranslateReleaseInput): Promise<TranslatedRelease> {
    const locales: Record<string, LocaleMetadata> = {};

    for (const locale of input.targetLocales) {
      locales[locale] = {
        locale,
        name: applyLockedTerms(translateText(input.source.name, locale), input, locale),
        subtitle: applyLockedTerms(translateText(input.source.subtitle, locale), input, locale),
        promotionalText: applyLockedTerms(
          translateText(input.source.promotionalText, locale),
          input,
          locale,
        ),
        description: applyLockedTerms(
          translateText(input.source.description, locale),
          input,
          locale,
        ),
        keywords: translateKeywords(input.source.keywords, locale),
        whatsNew: applyLockedTerms(translateText(input.source.whatsNew, locale), input, locale),
        supportUrl: input.source.supportUrl,
        marketingUrl: input.source.marketingUrl,
        reviewStatus: 'machine',
        translatorNotes: [
          `Generated by mock translator from ${input.sourceLocale}.`,
          'TODO: replace mock provider with a real translation provider when ready.',
        ],
      };
    }

    return { locales };
  }
}
